// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rilevazioniPresenzaData;

#nullable disable

namespace rilevazioniPresenzaData.Migrations
{
    [DbContext(typeof(RilevazionePresenzaContext))]
    [Migration("20250618124944_reduceRequired")]
    partial class reduceRequired
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("rilevazioniPresenzaData.Models.User", b =>
                {
                    b.Property<string>("Matricola")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Badge")
                        .HasColumnType("int");

                    b.Property<string>("Citta_Nascita")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codice_Fiscale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("Data_Nascita")
                        .HasColumnType("date");

                    b.Property<string>("Indirizzo_Residenza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nominativo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero_Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincia_Nascita")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincia_Residenza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sesso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stato_Civile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stato_Lavorativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stato_Nascita")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stato_Residenza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Matricola");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
