// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rilevazioniPresenzaData;

#nullable disable

namespace rilevazioniPresenzaData.Migrations
{
    [DbContext(typeof(RilevazionePresenzaContext))]
    [Migration("20250624130454_Stampings")]
    partial class Stampings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("rilevazioniPresenzaData.Models.Stamping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IdMatricola")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Orario")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShiftType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdMatricola");

                    b.ToTable("Stampings");
                });

            modelBuilder.Entity("rilevazioniPresenzaData.Models.User", b =>
                {
                    b.Property<string>("Matricola")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Admin")
                        .HasColumnType("bit");

                    b.Property<int>("Badge")
                        .HasColumnType("int");

                    b.Property<string>("Citta_Nascita")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codice_Fiscale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("Data_Nascita")
                        .HasColumnType("date");

                    b.Property<string>("Indirizzo_Residenza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nominativo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero_Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincia_Nascita")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincia_Residenza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sesso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stato_Civile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stato_Lavorativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stato_Nascita")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stato_Residenza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Matricola");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("rilevazioniPresenzaData.Models.UserShift", b =>
                {
                    b.Property<string>("IdMatricola")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Giorno")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("FT1")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("FT2")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("T1")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("T2")
                        .HasColumnType("time");

                    b.HasKey("IdMatricola", "Giorno");

                    b.ToTable("UserShifts");
                });

            modelBuilder.Entity("rilevazioniPresenzaData.Models.Stamping", b =>
                {
                    b.HasOne("rilevazioniPresenzaData.Models.User", "User")
                        .WithMany("Stampings")
                        .HasForeignKey("IdMatricola")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("rilevazioniPresenzaData.Models.UserShift", b =>
                {
                    b.HasOne("rilevazioniPresenzaData.Models.User", "User")
                        .WithMany("UserShifts")
                        .HasForeignKey("IdMatricola")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("rilevazioniPresenzaData.Models.User", b =>
                {
                    b.Navigation("Stampings");

                    b.Navigation("UserShifts");
                });
#pragma warning restore 612, 618
        }
    }
}
